function [first_switched] = FindFirstSwitched(patterns)
% Given pattern data, finds the node that switches to u- first, after the SDN.
%
% Inputs:
%   patterns - Mx(N+1) matrix, where M is the number of patterns and N is
%       the number of nodes. Generated by GetPatterns from
%       TangentContinuationLDS outputs.
%       
% Outputs:
%   first_switched - number or array. Index (or indices) of nodes that
%   switch first.


% ---------- BEGIN CODE ----------

    patterns = patterns(:,1:size(patterns,2)-1); % Remove parameter data column
    [M,N] = size(patterns);

    % Creating simplified pattern (bins into 0,u-,u+)
    simplified_pat = ones(M,N);
    for r = 1:M % loops over all patterns
        for c = 1:N % loops over u1 ... uN
            if patterns(r,c) > 0.8 % if u+
                simplified_pat(r,c) = 3;
            elseif patterns(r,c) > 0.3 % if u-
                simplified_pat(r,c) = 2;
            end
        end
    end

    % Finding first switched node by looking at row 3 (pattern after 2nd
    % fold) and finding the node at u-
    if size(simplified_pat,1) >= 3
        row3 = simplified_pat(3,:);
        first_switched = find(row3 == 2);
    else
        first_switched = "Error: <3 patterns for this node";
    end

end